## 1-  Data Science with python
### Numpy &ND array

#### Add a library

In [1]:
import numpy as np 

#### Make list 1 dimension

In [2]:
a = np.array([1,2,3,4,5,6])

#### Print variable 

In [3]:
print (a) 

[1 2 3 4 5 6]


#### If you need know the type 

In [4]:
print (type(a))  

<class 'numpy.ndarray'>


In [5]:
b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])# make list multidimension

In [6]:
print (b) # print 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


#### If you need know the type 

In [7]:
print (type(b)) 

<class 'numpy.ndarray'>


#### If you need make complex 

In [8]:
c = np.array([1,2,3,4,5,6],complex) 

In [9]:
print (c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


#### If you need know dimension we hvae function ( ndim )

In [10]:
print (c.ndim)

1


In [11]:
print(b.ndim)

2


 #### This function if you need know number of elements (bits)

In [12]:
print(c.itemsize)

16


In [13]:
print(b.itemsize)

4


In [14]:
print(a)

[1 2 3 4 5 6]


#### If you need know of each elements

In [15]:
print(a.dtype)

int32


In [16]:
a


array([1, 2, 3, 4, 5, 6])

In [17]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### If you need know of size element

In [18]:
print(a.size)

6


In [19]:
b.size

12

### Shape element
#### Useing this function (array.shape)
####  If you need know of shape element

In [20]:
print(a.shape)

(6,)


In [21]:
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
print(b.shape)

(2, 6)


#### Reshaping the array

In [40]:
my_array = np.array([[1,2,3,4],[7,8,9,10],[13,14,15,16]])

In [41]:
print(my_array)

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]]


In [42]:
print(my_array.shape)

(3, 4)


#### If you need of reshape (row,column)

In [47]:
my_array2 = my_array.reshape(4,3)

In [48]:
print(my_array.shape)

(3, 4)


In [49]:
print(my_array2)

[[ 1  2  3]
 [ 4  7  8]
 [ 9 10 13]
 [14 15 16]]


#### If you need of chopping the array

In [51]:
print (my_array2[1,1])

7


In [52]:
print (my_array2[2,2])

13


In [53]:
print (my_array2[3,1])

15


#### Arithmetic operation for array (+ , - , * , / )

In [56]:
my_array3 = np.array([[1,2,3,4],[7,8,9,10],[13,14,15,16]])

In [57]:
my_array4 = np.array([[17,18,19,20],[21,22,23,24],[25,26,27,28]])

In [58]:
print(my_array3 * my_array4)

[[ 17  36  57  80]
 [147 176 207 240]
 [325 364 405 448]]


print(my_array3 + my_array4)

In [60]:
print(my_array3 - my_array4)

[[-16 -16 -16 -16]
 [-14 -14 -14 -14]
 [-12 -12 -12 -12]]


In [61]:
print(my_array3 / my_array4)

[[0.05882353 0.11111111 0.15789474 0.2       ]
 [0.33333333 0.36363636 0.39130435 0.41666667]
 [0.52       0.53846154 0.55555556 0.57142857]]


#### Useing this functio horizontal stack - vertical stack

In [65]:
print( np.hstack((my_array3 , my_array4)) )

[[ 1  2  3  4 17 18 19 20]
 [ 7  8  9 10 21 22 23 24]
 [13 14 15 16 25 26 27 28]]


In [66]:
print( np.vstack((my_array3 , my_array4)) )

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]


# Good luck