In [1]:
import numpy as np

In [2]:
my_array = np.array([11,22,33,44,55,66,77,88,99,100])

In [4]:
my_array2 =  np.array([[11,22,33,44,55],[66,77,88,99,100]])

In [7]:
my_array4 = np.array([11,12,13,14,15])

In [8]:
my_array_total = my_array2 + my_array4 

In [9]:
print(my_array_total)

[[ 22  34  46  58  70]
 [ 77  89 101 113 115]]


In [12]:
my_array_total = my_array2 * my_array4 

In [13]:
print(my_array_total)

[[ 121  264  429  616  825]
 [ 726  924 1144 1386 1500]]


In [14]:
my_array_total = my_array2 - my_array4 

In [15]:
print(my_array_total)

[[ 0 10 20 30 40]
 [55 65 75 85 85]]


In [16]:
my_array_total = my_array2 / my_array4 

In [17]:
print(my_array_total)

[[1.         1.83333333 2.53846154 3.14285714 3.66666667]
 [6.         6.41666667 6.76923077 7.07142857 6.66666667]]


# Good luck