In [1]:
import numpy as np 

In [2]:
my_array = [0.11,3.44,6.50,6.77]

In [3]:
my_array

[0.11, 3.44, 6.5, 6.77]

#### This functions rounded to the largest (ceil)

In [4]:
my_array2 = np.ceil(my_array)

In [5]:
my_array

[0.11, 3.44, 6.5, 6.77]

In [6]:
my_array3 = [120.1,36.09844,62.50,6666.77]

In [7]:
my_array3

[120.1, 36.09844, 62.5, 6666.77]

In [8]:
my_array4 = np.ceil(my_array3)

In [9]:
my_array4

array([ 121.,   37.,   63., 6667.])

#### This functions rounded to the  (fix)

In [10]:
my_array5 = [1.1,2.2,5.6,8.9]

In [11]:
my_array5

[1.1, 2.2, 5.6, 8.9]

In [12]:
my_array6 = np.fix(my_array5)

In [13]:
my_array6

array([1., 2., 5., 8.])

#### This functions roundwd to the smaller (floor)

In [14]:
my_array7 = np.floor(my_array5)

In [15]:
my_array7

array([1., 2., 5., 8.])

In [16]:
my_array8 = [1.19999,2.287878787,5.356796,8.6432639]

In [17]:
my_array9= np.floor(my_array8)

In [18]:
my_array9

array([1., 2., 5., 8.])

#### This functions roundwd (rint) to the smaller (1,2,3,4,5) or largest (6,7,8,9,10)

In [19]:
int_array = [13.6,55.53,47.90898,13.88888]

In [20]:
int_array2 = [13.1,55.02,47.5777,13.88888]

In [21]:
int_array3= np.rint(int_array)

In [22]:
print(int_array)

[13.6, 55.53, 47.90898, 13.88888]


In [23]:
print(int_array3)

[14. 56. 48. 14.]


In [27]:
int_array4= np.rint(int_array2)

In [28]:
print(int_array4)

[13. 55. 48. 14.]


#### This functions is take 4 parameter

In [46]:
import numpy.matlib

In [48]:
myeyearray = np.matlib.eye(4 , k = 0 , dtype = float)

In [49]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [51]:
myeyearray2 = np.matlib.eye(4 , k = 0 , dtype = int)

In [52]:
myeyearray2

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [53]:
myeyearray3 = np.matlib.identity(6)

In [54]:
myeyearray3

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [55]:
myeyearray4 = np.matlib.identity(6 , dtype = int)

In [56]:
myeyearray4

matrix([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1]])

# Good luck